#!/bin/bash
if [ -d build];
	echo "Suppression du répertoire build existant !";
	then rm -rf build;
fi
echo "Création d'un répertoire build"
mkdir build
cd build
echo "Génération du Makefile par CMAKE" 
#cmake ../ -DCMAKE_SYSTEM_NAME=Linux
cmake ../ -G "MinGW Makefiles"

make 
#-DCMAKE_INSTALL_PREFIX=/usr ..
#echo "Dénération du Paquet Debian"
#cpack
#echo "test make package"
#make package 
echo "taille du paquet debian"
#ls -ltr *.deb 

#echo "Exécution du Makefile"
#make 
