#!/bin/bash
if [ -d build];
	echo "Suppression du répertoire build existant !";
	then rm -rf build;
fi
echo "Création d'un répertoire build"
mkdir build
cd build
echo "Génération du Makefile par CMAKE" 
cmake ../src
echo "Exécution du Makefile"
make 
